-- =============================================================================
-- V1__init.sql  –  Schema đầy đủ + Seed data mẫu
-- Tương thích H2 (dev/test) và PostgreSQL (prod)
-- =============================================================================

-- ── Users ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT uq_tenant_email UNIQUE (tenant_id, email)
);
CREATE INDEX IF NOT EXISTS idx_users_tenant_email ON users (tenant_id, email);

-- ── Product Type ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS product_type (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    syntax      VARCHAR(255) NOT NULL,
    description TEXT
);

-- ── Brand ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS brand (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    logo             VARCHAR(255),   -- path tới /static/images/brand/
    long_description TEXT            -- JSON array
);

-- ── Product (tạo trước vì ProductDetail FK về nó) ────────────────────────────
CREATE TABLE IF NOT EXISTS product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    syntax          VARCHAR(255),
    description     TEXT,
    price           NUMERIC(19, 2),
    is_sale_off     BOOLEAN NOT NULL DEFAULT FALSE,
    sale_percent    INT     DEFAULT 0,   -- % giảm giá, ví dụ: 20 = giảm 20%
    images          TEXT,                -- JSON array các path ảnh
    product_type_id BIGINT  NOT NULL REFERENCES product_type (id) ON DELETE RESTRICT
);

-- ── Product Detail (FK về Product) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS product_detail (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT  NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    is_vat              BOOLEAN NOT NULL DEFAULT FALSE,
    in_stock            BOOLEAN NOT NULL DEFAULT TRUE,
    short_description   TEXT,        -- JSON array
    summary_description TEXT,
    detail_description  TEXT,        -- JSON array
    final_description   TEXT,
    technical_functions TEXT,        -- JSON array
    brand_id            BIGINT REFERENCES brand (id) ON DELETE SET NULL
);

-- ── Promotion (ưu đãi theo thời gian, liên kết ProductDetail) ────────────────
CREATE TABLE IF NOT EXISTS promotion (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_detail_id BIGINT       NOT NULL REFERENCES product_detail (id) ON DELETE CASCADE,
    title             VARCHAR(255) NOT NULL,
    description       TEXT,
    start_date        DATE         NOT NULL,
    end_date          DATE         NOT NULL
);

-- =============================================================================
-- SEED DATA (dev / H2)
-- =============================================================================

-- ── Product Type ──────────────────────────────────────────────────────────────
INSERT INTO product_type (syntax, description) VALUES
    ('Di động',      'Điện thoại & SIM 4G/5G linh hoạt cho mọi nhu cầu'),
    ('Truyền hình',  'Trải nghiệm giải trí đỉnh cao với hàng trăm kênh HD'),
    ('Internet',     'Internet cáp quang tốc độ cao, ổn định 24/7'),
    ('Doanh nghiệp', 'Giải pháp kết nối toàn diện cho doanh nghiệp');

-- ── Brand ─────────────────────────────────────────────────────────────────────
INSERT INTO brand (name, logo, long_description) VALUES
    ('Viettel',  '/images/brand/viettel.png',  '["Mạng di động lớn nhất Việt Nam","Phủ sóng toàn quốc 63 tỉnh thành","Công nghệ 4G/5G tiên tiến"]'),
    ('VNPT',     '/images/brand/vnpt.png',     '["Tập đoàn viễn thông quốc gia","Hạ tầng cáp quang rộng khắp","Dịch vụ internet & truyền hình số"]'),
    ('FPT',      '/images/brand/fpt.png',      '["Nhà cung cấp internet hàng đầu","Tốc độ cao, ổn định","Hỗ trợ kỹ thuật 24/7"]'),
    ('MobiFone', '/images/brand/mobifone.png', '["Mạng di động uy tín","Gói cước đa dạng linh hoạt","Chất lượng dịch vụ xuất sắc"]');

-- ── Product ───────────────────────────────────────────────────────────────────
-- Di động (product_type_id = 1)
INSERT INTO product (syntax, description, price, is_sale_off, sale_percent, images, product_type_id) VALUES
    ('SIM 4G Viettel 7GB',        'Gói data 7GB tốc độ cao, gọi nội mạng miễn phí',        70000,  FALSE, 0,  '["/images/product/sim-viettel-7gb.png"]',    1),
    ('SIM 4G Viettel 30GB',       'Gói data 30GB, gọi miễn phí nội & ngoại mạng',           150000, TRUE,  20, '["/images/product/sim-viettel-30gb.png"]',   1),
    ('SIM 5G MobiFone Unlimited', 'Data không giới hạn, tốc độ 5G khi có vùng phủ',         250000, FALSE, 0,  '["/images/product/sim-mobi-unlimited.png"]', 1),
    ('SIM Sinh viên 15GB',        'Ưu đãi đặc biệt cho sinh viên, 15GB/tháng',               90000,  TRUE,  15, '["/images/product/sim-sinhvien.png"]',       1);

-- Truyền hình (product_type_id = 2)
INSERT INTO product (syntax, description, price, is_sale_off, sale_percent, images, product_type_id) VALUES
    ('Truyền hình Cơ bản',   '100+ kênh HD, kho VOD 500 phim',                          80000,  FALSE, 0,  '["/images/product/tv-basic.png"]',   2),
    ('Truyền hình Gia đình', '200+ kênh HD/4K, VOD không giới hạn, 3 thiết bị',         150000, FALSE, 0,  '["/images/product/tv-family.png"]',  2),
    ('Truyền hình Premium',  '250+ kênh HD/4K/8K, thể thao quốc tế, đa thiết bị',       250000, TRUE,  10, '["/images/product/tv-premium.png"]', 2);

-- Internet (product_type_id = 3)
INSERT INTO product (syntax, description, price, is_sale_off, sale_percent, images, product_type_id) VALUES
    ('Internet 50Mbps',  'Tốc độ 50Mbps, không giới hạn data, modem miễn phí',     150000, FALSE, 0,  '["/images/product/inet-basic.png"]',    3),
    ('Internet 200Mbps', 'Tốc độ 200Mbps, router Wi-Fi 6, hỗ trợ 24/7',            250000, TRUE,  25, '["/images/product/inet-standard.png"]', 3),
    ('Internet 1Gbps',   'Tốc độ 1Gbps, Mesh Wi-Fi 6, SLA cam kết 99.9%',          450000, FALSE, 0,  '["/images/product/inet-premium.png"]',  3);

-- Doanh nghiệp (product_type_id = 4)
INSERT INTO product (syntax, description, price, is_sale_off, sale_percent, images, product_type_id) VALUES
    ('Leased Line 100Mbps', 'Đường truyền riêng đối xứng, SLA 99.99%, 24/7',         NULL, FALSE, 0, '["/images/product/biz-leasedline.png"]', 4),
    ('VPN & MPLS',          'Kết nối văn phòng nhánh bảo mật, QoS ưu tiên',          NULL, FALSE, 0, '["/images/product/biz-vpn.png"]',        4),
    ('Cloud Hosting',       'Server ảo, lưu trữ đám mây, CDN, data center Tier 3',   NULL, FALSE, 0, '["/images/product/biz-cloud.png"]',      4);

-- ── Product Detail (product_id tham chiếu tới product.id) ────────────────────
-- product_id=1: SIM 4G Viettel 7GB
INSERT INTO product_detail (product_id, is_vat, in_stock, short_description, summary_description, detail_description, final_description, technical_functions, brand_id) VALUES
    (1, FALSE, TRUE,
     '["7GB data tốc độ cao","Gọi nội mạng miễn phí","100 phút ngoại mạng"]',
     'Gói SIM phổ thông dành cho người dùng cơ bản.',
     '["Gói SIM 4G Viettel 7GB là lựa chọn tiết kiệm cho người dùng cơ bản.","Cung cấp 7GB data tốc độ cao mỗi tháng, phù hợp lướt web, mạng xã hội hàng ngày.","Gọi nội mạng Viettel miễn phí không giới hạn, tiết kiệm chi phí liên lạc.","Hỗ trợ công nghệ VoLTE giúp cuộc gọi rõ ràng hơn trên nền 4G."]',
     'Liên hệ hotline 18008168 để đăng ký ngay hôm nay.',
     '["Công nghệ: 4G LTE Cat.6 – Hỗ trợ tốc độ download tối đa 150Mbps","VoLTE: Cuộc gọi HD trên nền mạng 4G, chất lượng rõ ràng hơn 3G","VoWifi: Gọi qua Wi-Fi khi ở vùng sóng yếu","Vùng phủ: 95% dân số toàn quốc"]',
     1);

-- product_id=2: SIM 4G Viettel 30GB
INSERT INTO product_detail (product_id, is_vat, in_stock, short_description, summary_description, detail_description, final_description, technical_functions, brand_id) VALUES
    (2, FALSE, TRUE,
     '["30GB data tốc độ cao","Gọi miễn phí nội & ngoại mạng","Roaming 10 quốc gia"]',
     'Gói SIM phổ biến nhất, phù hợp mọi đối tượng.',
     '["SIM 4G Viettel 30GB là gói cước bán chạy nhất với data dồi dào cho mọi nhu cầu.","30GB data tốc độ 4G/5G mỗi tháng, xem video HD, họp online mượt mà.","Gọi miễn phí nội mạng và ngoại mạng không giới hạn, không lo tốn cước.","Hỗ trợ Roaming tại 10 quốc gia châu Á, tiện lợi khi đi công tác hoặc du lịch."]',
     'Đăng ký qua app MyViettel hoặc USSD *098#.',
     '["Công nghệ: 4G/5G – Tốc độ download tối đa 500Mbps trên 5G","VoLTE: Gọi HD chất lượng cao trên nền 4G","Roaming quốc tế: Hỗ trợ 10 quốc gia khu vực châu Á","Data sau ngưỡng: Tốc độ giảm còn 64Kbps khi hết 30GB"]',
     1);

-- product_id=9: Internet 200Mbps
INSERT INTO product_detail (product_id, is_vat, in_stock, short_description, summary_description, detail_description, final_description, technical_functions, brand_id) VALUES
    (9, TRUE, TRUE,
     '["Tốc độ 200Mbps","Router Wi-Fi 6 miễn phí","Lắp đặt miễn phí"]',
     'Gói internet gia đình được lựa chọn nhiều nhất.',
     '["Gói Internet 200Mbps của FPT mang đến trải nghiệm lướt web cực nhanh cho cả gia đình.","Tốc độ đối xứng 200Mbps cả upload lẫn download, phù hợp làm việc từ xa và giải trí.","Router Wi-Fi 6 được tặng kèm, hỗ trợ đến 64 thiết bị kết nối đồng thời.","Cam kết uptime 99.5% với đội ngũ kỹ thuật hỗ trợ tận nhà 24/7."]',
     'Hotline hỗ trợ kỹ thuật: 1800 599 900 (miễn phí).',
     '["Công nghệ: GPON Fiber – Cáp quang thế hệ mới, độ trễ thấp","Wi-Fi: Wi-Fi 6 (802.11ax) – Băng tần kép 2.4GHz + 5GHz","Thiết bị đồng thời: Hỗ trợ tối đa 64 thiết bị kết nối cùng lúc","IPv6: Hỗ trợ IPv4 + IPv6 dual stack","Uptime: Cam kết 99.5% SLA hàng tháng"]',
     3);

-- ── Promotion ─────────────────────────────────────────────────────────────────
-- product_detail_id=1 (SIM 4G Viettel 7GB)
INSERT INTO promotion (product_detail_id, title, description, start_date, end_date) VALUES
    (1, 'Tặng 1GB tháng đầu',      'Đăng ký mới trong tháng 4/2026 được tặng thêm 1GB data sử dụng ngay tháng đầu tiên.', '2026-04-01', '2026-04-30'),
    (1, 'Miễn phí SIM vật lý',     'Miễn phí SIM vật lý hoặc eSIM khi đăng ký online qua app MyViettel.',                  '2026-04-01', '2026-06-30');

-- product_detail_id=2 (SIM 4G Viettel 30GB)
INSERT INTO promotion (product_detail_id, title, description, start_date, end_date) VALUES
    (2, 'Giảm 20% tháng đầu',      'Áp dụng giảm 20% cước tháng đầu tiên cho khách hàng đăng ký mới trong tháng 4/2026.', '2026-04-01', '2026-04-30'),
    (2, 'Roaming miễn phí 3 ngày', 'Tặng 3 ngày Roaming miễn phí tại Thái Lan, Campuchia hoặc Singapore.',                 '2026-03-01', '2026-05-31');

-- product_detail_id=3 (Internet 200Mbps)
INSERT INTO promotion (product_detail_id, title, description, start_date, end_date) VALUES
    (3, 'Tặng 2 tháng miễn phí',   'Đăng ký gói 1 năm được tặng thêm 2 tháng sử dụng miễn phí, tiết kiệm đến 500.000đ.', '2026-04-01', '2026-05-31'),
    (3, 'Lắp đặt miễn phí',        'Miễn phí toàn bộ chi phí lắp đặt và thiết bị router Wi-Fi 6 cho khách hàng mới.',      '2026-01-01', '2026-12-31');

